import io
import uuid
import zipfile
from pathlib import Path
from fastapi import APIRouter, UploadFile, File, HTTPException, Depends
from fastapi.responses import FileResponse, StreamingResponse
from sqlalchemy.orm import Session

from pipelines.transcriber import transcribe_audio
from pipelines.midi_analyzer import analyze_midi
from database import get_db, User, Generation
from middleware.auth import get_current_user

router = APIRouter()
UPLOAD_DIR = Path("/tmp/voxmidi")
MIDI_STORE = Path("/app/data/midi")


@router.post("/transcribe")
async def transcribe(
    audio: UploadFile = File(...),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Transcribe uploaded audio to MIDI using Basic Pitch."""
    if current_user.usage_count >= current_user.usage_limit:
        raise HTTPException(status_code=429, detail=f"Monthly limit of {current_user.usage_limit} reached")

    job_id = str(uuid.uuid4())[:8]
    job_dir = UPLOAD_DIR / job_id
    job_dir.mkdir(parents=True, exist_ok=True)

    audio_path = job_dir / "input.wav"
    content = await audio.read()
    audio_path.write_bytes(content)

    try:
        midi_path = transcribe_audio(str(audio_path), str(job_dir))
        analysis = analyze_midi(midi_path)

        # Record generation
        gen = Generation(
            id=job_id,
            user_id=current_user.id,
            mode="transcribe",
            genre="unknown",
            tracks_count=len(analysis.get("tracks", [])),
            duration=analysis.get("duration", 0.0),
            time_signature=analysis.get("time_signature", "4/4"),
            midi_filename="output.mid",
        )
        db.add(gen)
        current_user.usage_count += 1
        db.commit()

        return {
            "job_id": job_id,
            "midi_url": f"/api/download/{job_id}/output.mid",
            **analysis,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/download/{job_id}/{filename}")
async def download_file(job_id: str, filename: str):
    """Download a generated file. Checks persistent store first, then /tmp."""
    if filename == "stems.zip":
        return await _stems_zip(job_id)

    for base in (MIDI_STORE, UPLOAD_DIR):
        file_path = base / job_id / filename
        if file_path.exists():
            if filename.endswith(".mp3"):
                media_type = "audio/mpeg"
            elif filename.endswith(".wav"):
                media_type = "audio/wav"
            elif filename.endswith(".mid"):
                media_type = "audio/midi"
            else:
                media_type = "application/octet-stream"
            return FileResponse(
                str(file_path),
                media_type=media_type,
                filename=filename,
                headers={"Content-Disposition": f'attachment; filename="{filename}"'},
            )
    raise HTTPException(status_code=404, detail="File not found")


async def _stems_zip(job_id: str) -> StreamingResponse:
    """Stream a zip of all stem MP3s plus a DAW import README."""
    STEM_NAMES = ["vocals", "bass", "drums", "other"]
    buf = io.BytesIO()
    found = False
    tempo = 120
    key = "Am"

    # Try to get metadata from DB
    try:
        from database import SessionLocal, Generation
        _db = SessionLocal()
        gen = _db.query(Generation).filter(Generation.id == job_id).first()
        if gen:
            tempo = gen.tempo or 120
            key = gen.key or "Am"
        _db.close()
    except Exception:
        pass

    readme = f"""HOW TO IMPORT INTO YOUR DAW
Generated by VoxMIDI — Tempo: {tempo} BPM, Key: {key}

GARAGEBAND
1. File → New
2. Drag vocals.mp3, bass.mp3, drums.mp3, other.mp3 onto separate audio tracks
3. File → Import → MIDI → select output.mid for editable notes
4. Set project tempo to {tempo} BPM

ABLETON LIVE
1. Create new project, set tempo to {tempo}
2. Drag stem files onto separate audio tracks in Arrangement view
3. Drag output.mid onto a MIDI track for editable notes

FL STUDIO
1. File → Import audio files, drop stems onto Channel Rack
2. Set project tempo to {tempo}
3. File → Import MIDI → output.mid

LOGIC PRO
1. File → New, set tempo to {tempo}
2. Drag stems to audio tracks
3. File → Import MIDI File → output.mid for editable notes

PRO TOOLS
1. Create new session at {tempo} BPM
2. File → Import → Audio → select stem files
3. File → Import → MIDI → output.mid
"""

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for base in (MIDI_STORE, UPLOAD_DIR):
            job_dir = base / job_id
            if not job_dir.exists():
                continue
            for stem in STEM_NAMES:
                src = job_dir / f"{stem}.mp3"
                if src.exists():
                    zf.write(src, f"{stem}.mp3")
                    found = True
            # Full mix
            for name in ("musicgen_audio.mp3", "minimax_audio.mp3", "full_mix.mp3"):
                src = job_dir / name
                if src.exists():
                    zf.write(src, "full_mix.mp3")
                    found = True
                    break
            # MIDI
            for name in ("output.mid", "final.mid"):
                src = job_dir / name
                if src.exists():
                    zf.write(src, "output.mid")
                    break
            if found:
                break

    if not found:
        raise HTTPException(status_code=404, detail="No stems found")

    # Add README outside the found loop (always include)
    with zipfile.ZipFile(buf, "a", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.txt", readme)

    buf.seek(0)
    zip_name = f"voxmidi_{job_id}_stems.zip"
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{zip_name}"'},
    )
